# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setMaximumSize(QtCore.QSize(500, 700))
        MainWindow.setStyleSheet("")
        MainWindow.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.FramelessWindowHint)
        MainWindow.setAttribute(Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 461, 651))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:#000000;\n"
"border-top-left-radius: 200px;\n"
"border-bottom-right-radius: 200px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"QFrame::hover{\n"
"border-top-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-right-radius: 200px;\n"
"border-bottom-left-radius: 200px;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_Exit = QtWidgets.QPushButton(self.frame)
        self.btn_Exit.setGeometry(QtCore.QRect(120, 530, 221, 21))
        self.btn_Exit.setStyleSheet("QPushButton{\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"")
        self.btn_Exit.setObjectName("btn_Exit")
        self.lbl_DorkScanner = QtWidgets.QLabel(self.frame)
        self.lbl_DorkScanner.setGeometry(QtCore.QRect(80, 120, 311, 51))
        self.lbl_DorkScanner.setStyleSheet("QLabel{\n"
"color: rgb(255, 0, 0);\n"
"    font: 75 24pt \"Cambria\";\n"
"\n"
"}\n"
"QLabel::hover{\n"
"color:#ffffff;\n"
"}")
        self.lbl_DorkScanner.setObjectName("lbl_DorkScanner")
        self.btn_Github = QtWidgets.QPushButton(self.frame)
        self.btn_Github.setGeometry(QtCore.QRect(190, 570, 81, 41))
        self.btn_Github.setStyleSheet("QPushButton{\n"
"\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: #fff;\n"
"    color:#fff;\n"
"    \n"
"}\n"
"\n"
"")
        self.btn_Github.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/GitHub/GitHub_Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Github.setIcon(icon)
        self.btn_Github.setIconSize(QtCore.QSize(68, 68))
        self.btn_Github.setObjectName("btn_Github")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 190, 121, 76))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_DorkType = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_DorkType.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Cambria\";")
        self.lbl_DorkType.setObjectName("lbl_DorkType")
        self.verticalLayout.addWidget(self.lbl_DorkType)
        self.cmb_Dork = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmb_Dork.setFont(font)
        self.cmb_Dork.setStyleSheet("QComboBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"text-align: center;\n"
"\n"
"}\n"
"QComboBox::hover{\n"
"background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QComboBox::pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.cmb_Dork.setObjectName("cmb_Dork")
        self.verticalLayout.addWidget(self.cmb_Dork)
        self.btn_Start = QtWidgets.QPushButton(self.frame)
        self.btn_Start.setGeometry(QtCore.QRect(190, 470, 81, 41))
        self.btn_Start.setStyleSheet("QPushButton{\n"
"\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"    background-color: #000;\n"
"    color:#fff;\n"
"    \n"
"}\n"
"\n"
"")
        self.btn_Start.setIconSize(QtCore.QSize(68, 68))
        self.btn_Start.setObjectName("btn_Start")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(250, 190, 121, 76))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_SelectDork = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lbl_SelectDork.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Cambria\";")
        self.lbl_SelectDork.setObjectName("lbl_SelectDork")
        self.verticalLayout_4.addWidget(self.lbl_SelectDork)
        self.cmb_SelectDock = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmb_SelectDock.setFont(font)
        self.cmb_SelectDock.setStyleSheet("QComboBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"text-align: center;\n"
"\n"
"}\n"
"QComboBox::hover{\n"
"background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QComboBox::pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.cmb_SelectDock.setObjectName("cmb_SelectDock")
        self.verticalLayout_4.addWidget(self.cmb_SelectDock)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(100, 280, 121, 76))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_SelectNumber = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_SelectNumber.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Cambria\";")
        self.lbl_SelectNumber.setObjectName("lbl_SelectNumber")
        self.verticalLayout_3.addWidget(self.lbl_SelectNumber)
        self.cmb_Number = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmb_Number.setFont(font)
        self.cmb_Number.setStyleSheet("QComboBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"text-align: center;\n"
"\n"
"}\n"
"QComboBox::hover{\n"
"background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QComboBox::pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.cmb_Number.setObjectName("cmb_Number")
        self.verticalLayout_3.addWidget(self.cmb_Number)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 280, 121, 76))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_SelectDorkLanguage = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_SelectDorkLanguage.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Cambria\";")
        self.lbl_SelectDorkLanguage.setObjectName("lbl_SelectDorkLanguage")
        self.verticalLayout_2.addWidget(self.lbl_SelectDorkLanguage)
        self.cmb_DorkLanguage = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmb_DorkLanguage.setFont(font)
        self.cmb_DorkLanguage.setStyleSheet("QComboBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"text-align: center;\n"
"\n"
"}\n"
"QComboBox::hover{\n"
"background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QComboBox::pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.cmb_DorkLanguage.setObjectName("cmb_DorkLanguage")
        self.verticalLayout_2.addWidget(self.cmb_DorkLanguage)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(100, 380, 271, 76))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_SelectLanguage = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lbl_SelectLanguage.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Cambria\";")
        self.lbl_SelectLanguage.setObjectName("lbl_SelectLanguage")
        self.verticalLayout_5.addWidget(self.lbl_SelectLanguage)
        self.cmb_Language = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmb_Language.setFont(font)
        self.cmb_Language.setStyleSheet("QComboBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"text-align: center;\n"
"\n"
"}\n"
"QComboBox::hover{\n"
"background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QComboBox::pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.cmb_Language.setObjectName("cmb_Language")
        self.verticalLayout_5.addWidget(self.cmb_Language)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Exit.setText(_translate("MainWindow", "Exit"))
        self.lbl_DorkScanner.setText(_translate("MainWindow", "Agartha Dork Scanner"))
        self.btn_Github.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/exit/buymeacoffee_logo_icon_169441.png\"/></p></body></html>"))
        self.lbl_DorkType.setText(_translate("MainWindow", "Dork Type"))
        self.btn_Start.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/exit/buymeacoffee_logo_icon_169441.png\"/></p></body></html>"))
        self.btn_Start.setText(_translate("MainWindow", "Start"))
        self.lbl_SelectDork.setText(_translate("MainWindow", "Select A Dork"))
        self.lbl_SelectNumber.setText(_translate("MainWindow", "Number"))
        self.lbl_SelectDorkLanguage.setText(_translate("MainWindow", "Dork Language"))
        self.lbl_SelectLanguage.setText(_translate("MainWindow", "Select Language"))
import Assets.resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
